let network,cy;let colorAttribute='Modularity Class',sizeAttribute='Degree',groupAttribute='none';
const palette=['#386cb0','#fdb462','#7fc97f','#ef3b2c','#beaed4','#fdc086','#ffff99','#666666','#1b9e77','#d95f02','#7570b3','#e7298a','#66a61e','#e6ab02','#a6761d','#1f78b4'];
const $=id=>document.getElementById(id);const skip=new Set(['id','original_id','Question','Answer','x','y','#','label','combined_text']);
async function init(){network=await fetch('data/network.json').then(r=>r.json());$('stats').textContent=`${network.metadata.nodes.toLocaleString()} nodes · ${network.metadata.edges.toLocaleString()} edges`;
 const keys=[...new Set(network.nodes.flatMap(n=>Object.keys(n)))].filter(k=>!skip.has(k)); const numeric=keys.filter(k=>network.nodes.some(n=>typeof n[k]==='number')); const categorical=keys.filter(k=>!numeric.includes(k));
 fill($('colorBy'),keys);fill($('sizeBy'),numeric);fill($('groupBy'),categorical);$('colorBy').value='Modularity Class';$('sizeBy').value='Degree';
 const elements=[...network.nodes.map(n=>({data:n,position:{x:Number(n.x)||0,y:Number(n.y)||0}})),...network.edges.map(e=>({data:e}))];
 cy=cytoscape({container:$('cy'),elements,pixelRatio:1,wheelSensitivity:.25,style:[{selector:'node',style:{'background-color':nodeColor,width:nodeSize,height:nodeSize,'border-width':.8,'border-color':'#fff'}},{selector:'node:selected',style:{'border-width':3,'border-color':'#111827'}},{selector:'edge',style:{width:edgeWidth,'line-color':'#9aa3b2',opacity:parseFloat($('edgeOpacity').value),'curve-style':'haystack'}},{selector:'.dim',style:{opacity:.07}},{selector:'.focus',style:{opacity:1}}],layout:{name:'preset',fit:true,padding:30}});
 cy.on('mouseover','node',e=>inspectNode(e.target,false));cy.on('tap','node',e=>inspectNode(e.target,true));cy.on('tap',e=>{if(e.target===cy)clearInspector()});
 $('colorBy').onchange=e=>{colorAttribute=e.target.value;updateStyle()};$('sizeBy').onchange=e=>{sizeAttribute=e.target.value;updateStyle()};$('groupBy').onchange=e=>{groupAttribute=e.target.value; if(groupAttribute!=='none') $('layout').value='concentric';runLayout();renderLegend()};$('sizeScale').oninput=updateStyle;$('edgeOpacity').oninput=updateStyle;$('layout').onchange=runLayout;$('fit').onclick=()=>cy.fit(cy.nodes(':visible'),30);$('resetStyle').onclick=resetStyle;$('downloadPng').onclick=exportPNG;$('resetFilters').onclick=resetFilters;$('search').oninput=applyFilters;$('minDegree').oninput=()=>{$('degreeValue').textContent=$('minDegree').value;applyFilters()};$('loading').style.display='none';updateStyle();renderLegend();}
function fill(sel,vals){sel.innerHTML='';vals.forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=pretty(v);sel.appendChild(o)})}function pretty(v){return v.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function nums(a){return network.nodes.map(n=>Number(n[a])).filter(Number.isFinite)}function range(a){let v=nums(a);return v.length?[Math.min(...v),Math.max(...v)]:[0,1]}function norm(v,a,b){return a===b?.5:(Number(v)-a)/(b-a)}
function nodeSize(n){let [a,b]=range(sizeAttribute),t=Math.max(0,norm(n.data(sizeAttribute),a,b));return(7+Math.sqrt(t)*20)*parseFloat($('sizeScale').value)}function nodeColor(n){let v=n.data(colorAttribute);if(colorAttribute==='Modularity Class')return palette[Math.abs(Number(v)||0)%palette.length];if(typeof v==='number'){let[a,b]=range(colorAttribute),t=norm(v,a,b);return `hsl(${220-200*t},72%,${48+10*(1-t)}%)`}let h=0;String(v??'').split('').forEach(c=>h=((h<<5)-h+c.charCodeAt(0))|0);return palette[Math.abs(h)%palette.length]}
function edgeWidth(e){return Math.max(.5,Math.min(6,.5+Math.log1p(Number(e.data('weight'))||1)*.55))}function updateStyle(){if(!cy)return;cy.nodes().forEach(n=>{n.style('background-color',nodeColor(n));n.style('width',nodeSize(n));n.style('height',nodeSize(n))});cy.edges().forEach(e=>e.style('opacity',parseFloat($('edgeOpacity').value)));renderLegend()}
function runLayout(){let name=$('layout').value;if(name==='preset'){cy.layout({name:'preset',fit:true,padding:30}).run();return}let opts={name,fit:true,padding:45,animate:name==='cose',idealEdgeLength:90,nodeRepulsion:5000,gravity:.25};if(name==='concentric'){let vals=[...new Set(network.nodes.map(n=>String(n.data?.[groupAttribute]??'')))];opts.concentric=n=>{let v=String(n.data(groupAttribute)??'');return vals.indexOf(v)+1};opts.levelWidth=()=>1}cy.layout(opts).run()}
function inspectNode(node,center){cy.elements().removeClass('dim focus');node.neighborhood().add(node).addClass('focus');if(center)cy.animate({fit:{eles:node.neighborhood().add(node),padding:100},duration:250});renderInspector(node)}
function renderInspector(node){let d=node.data(),neigh=node.neighborhood('node').sort((a,b)=>(b.data('weight')||0)-(a.data('weight')||0));let attrs=Object.keys(d).filter(k=>!['id','original_id','Question','Answer','x','y','#','combined_text'].includes(k)).sort();let meta=attrs.map(k=>`<div><b>${escapeHtml(pretty(k))}</b><span>${escapeHtml(String(d[k]??''))}</span></div>`).join('');let con=neigh.slice(0,14).map(n=>`<div class="connection" data-node="${escapeHtml(n.id())}"><span class="connection-id">${escapeHtml(String(n.data().id))}</span>${escapeHtml(truncate(String(n.data().Answer||''),150))}</div>`).join('');$('inspector').innerHTML=`<h2 class="node-title">Node ${escapeHtml(String(d.id))}</h2><div class="node-id">${escapeHtml(String(d['#']||''))}</div><div class="card"><h3>Question</h3><p>${escapeHtml(d.Question||'Not available')}</p></div><div class="card answer-card"><h3>Answer</h3><p>${escapeHtml(d.Answer||'Not available')}</p></div><div class="card"><h3>Network attributes</h3><div class="meta">${meta}</div></div><div class="card"><h3>Connected nodes (${neigh.length})</h3>${con||'<p>No connected nodes.</p>'}</div>`;document.querySelectorAll('.connection').forEach(el=>el.onclick=()=>{let t=cy.getElementById(el.dataset.node);if(t.nonempty())inspectNode(t,true)})}
function clearInspector(){cy.elements().removeClass('dim focus');$('inspector').innerHTML='<div class="inspector-empty"><div class="big-icon">◉</div><h2>Inspect a node</h2><p>Hover over a node to inspect its response. Click it to centre the network on that node.</p></div>'}
function applyFilters(){let q=$('search').value.trim().toLowerCase(),min=Number($('minDegree').value);cy.nodes().forEach(n=>{let d=n.data(),hay=[d.id,d['#'],d.Question,d.Answer,d.Year,d.Month,d.Village,d.Source_Sheet].filter(Boolean).join(' ').toLowerCase();n.style('display',d.Degree>=min&&(!q||hay.includes(q))?'element':'none')})}
function resetFilters(){$('search').value='';$('minDegree').value=0;$('degreeValue').textContent='0';cy.nodes().style('display','element')}
function resetStyle(){$('colorBy').value='Modularity Class';$('sizeBy').value='Degree';$('groupBy').value='none';$('sizeScale').value=1;$('edgeOpacity').value=.35;$('layout').value='preset';colorAttribute='Modularity Class';sizeAttribute='Degree';groupAttribute='none';updateStyle();runLayout()}
function renderLegend(){let el=$('legend');if(colorAttribute==='Modularity Class'){el.innerHTML=palette.slice(0,12).map((c,i)=>`<div class="legend-item"><span class="swatch" style="background:${c}"></span>Community ${i}</div>`).join('')}else if(nums(colorAttribute).length){el.innerHTML='<div class="legend-item">Continuous scale: lower → higher</div>'}else el.innerHTML='<div class="legend-item">Categorical colours are assigned consistently.</div>'}
function exportPNG(){let a=document.createElement('a');a.href=cy.png({full:true,scale:2,bg:'#fbfcfe'});a.download='semantic-network.png';a.click()}function truncate(s,n){return s.length>n?s.slice(0,n-1)+'…':s}function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}init().catch(e=>{$('loading').textContent='Could not load network.json.';console.error(e)});
